### ISSUE TITLE
Humble colcon build failed

### ISSUE THREAD

**Issue by Ragnar7982** [open-navigation/opennav_coverage#79] opened 2024-11-12 11:33 UTC
Hello, I am using ubuntu22.04 and ros2 humble, I already see #58 to fix the problems, but still encoutered some errors, here were the steps I've done:
1. create a workspace and src
2. download and extract Fields2Cover-1.2.1.zip and opennav_coverage-humble.zip files to src
3. cd Fields2Cover-1.2.1 and mkdir - p build
4. cd build, cmake -DCMAKE_BUILD_TYPE=Release .. ;  make -j$(nproc);  sudo make install;
5. cd workspace, the colcon build --base-paths src/ --symlink-install
I got the errors when I was colcon build:
Starting >>> opennav_coverage_msgs
Starting >>> fields2cover
Starting >>> backported_bt_navigator
Finished <<< backported_bt_navigator [0.41s]
Finished <<< fields2cover [0.59s]                                           
Finished <<< opennav_coverage_msgs [0.90s]                  
Starting >>> opennav_coverage
Starting >>> opennav_coverage_bt
Finished <<< opennav_coverage_bt [0.32s]                                 
--- stderr: opennav_coverage                             
/usr/bin/ld: CMakeFiles/test_viz.dir/test_viz.cpp.o: undefined reference to symbol '_ZNK11OGRGeometry11exportToWktEPPc13OGRwkbVariant'
/usr/bin/ld: /lib/libgdal.so.30: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [test/CMakeFiles/test_viz.dir/build.make:461: test/test_viz] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:298: test/CMakeFiles/test_viz.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< opennav_coverage [0.79s, exited with code 2]

Summary: 4 packages finished [1.90s]
  1 package failed: opennav_coverage
  1 package had stderr output: opennav_coverage
  3 packages not processed
I don't know what's happened, but I did the exactly @grboguz21 and @emusman-lab did, can someone tell me where I did it wrong?
Here is the details:
![image](https://github.com/user-attachments/assets/ec5fe44f-d226-4801-97e2-def816c676b3)

Thank you!

**Comment by SteveMacenski** [comment] 2024-12-02 22:45
Duplicate of https://github.com/open-navigation/opennav_coverage/issues/77

**Closed by SteveMacenski** 2024-12-02 22:45 UTC
