### ISSUE TITLE
Working with WGS84

### ISSUE THREAD

**Issue by MarcM0** [open-navigation/opennav_coverage#61] opened 2024-06-17 19:16 UTC
I am getting this error when running in iron `Internal Fields2Cover error: Geometry does not contain point 0` when I try to pass in a message in the wgs84 frame. 

```
        goal_msg = NavigateCompleteCoverage.Goal()
        goal_msg.frame_id = 'wgs84'
        goal_msg.polygons.append(self.toPolygon(field))

        print('Navigating to with field of size: ' + str(len(field)) + '...')
        send_goal_future = self.coverage_client.send_goal_async(goal_msg,
                                                                self._feedbackCallback)
        rclpy.spin_until_future_complete(self, send_goal_future)
        self.goal_handle = send_goal_future.result()
```

I saw some talk about this in https://github.com/Fields2Cover/Fields2Cover/issues/73 , but shouldnt it convert to meters once frameID is given?

Thanks in advance

**Comment by SteveMacenski** [comment] 2024-06-18 15:58
That usually means you didn't populate the message properly. Check out unit tests, F2C examples for examples :smile:

**Comment by MarcM0** [comment] 2024-06-19 22:39
I am passing the following [[-79.39132331041327, 43.63785348799382], [-79.39100734829563, 43.63703885671455], [-79.38967868708299, 43.63720295510174], [-79.38994603964407, 43.638023447037696], [-79.39132331041327, 43.63785348799382]] into these functions, which are identical to the demo, except that I added a frameid argument. 

```
def toPolygon(self, field):
        poly = Polygon()
        for coord in field:
            pt = Point32()
            pt.x = coord[0]
            pt.y = coord[1]
            poly.points.append(pt)
        return poly
    
    def navigateCoverage(self, field,frame_id):
        """Send a `NavToPose` action request."""
        print("Waiting for 'NavigateCompleteCoverage' action server")
        while not self.coverage_client.wait_for_server(timeout_sec=1.0):
            print('"NavigateCompleteCoverage" action server not available, waiting...')

        goal_msg = NavigateCompleteCoverage.Goal()
        goal_msg.frame_id = frame_id
        goal_msg.polygons.append(self.toPolygon(field))

        print('Navigating to with field of size: ' + str(len(field)) + '...')
        send_goal_future = self.coverage_client.send_goal_async(goal_msg,
                                                                self._feedbackCallback)
        rclpy.spin_until_future_complete(self, send_goal_future)
        self.goal_handle = send_goal_future.result()

        if not self.goal_handle.accepted:
            print('Navigate Coverage request was rejected!')
            return False

        self.result_future = self.goal_handle.get_result_async()
        return True

```
The goes away I pick a MUCH larger area

**Comment by SteveMacenski** [comment] 2024-06-20 15:51
Are you properly setting the cartesian flags? This sounds like an issue with that: `coordinates_in_cartesian_frame`

**Comment by MarcM0** [comment] 2024-06-20 19:03
I see, thanks, now I get Invalid GML File or Coordinates: Coordinate system not recognized
Here are my params
```
coverage_server:
  ros__parameters:
    use_sim_time: True
    default_headland_width: 0.25
    robot_width: 0.7
    operation_width: 0.7
    min_turning_radius: 0.35
    linear_curv_change: 200.0
    coordinates_in_cartesian_frame: false
    default_allow_overlap: false
    default_swath_angle_type: "SET_ANGLE"
    default_swath_angle: 0.0 # We know its aligned for the demo
```

**Comment by SteveMacenski** [comment] 2024-06-20 19:36
I think you need to use caps `WGS84`

**Comment by MarcM0** [comment] 2024-06-20 20:12
Thank you again, might want to update that in the documentation (currently says coordinates_in_cartesian_frame 	Whether incoming requests are in cartesian or GPS coordinates 	bool)

Now it says 
```
[interactive_waypoint_follower_fields-12] Waiting for 'NavigateCompleteCoverage' action server
[interactive_waypoint_follower_fields-12] Navigating to with field of size: 5...
```
but doesnt actually move

**Comment by MarcM0** [comment] 2024-06-20 20:28
Actually, I also get this earlier
`[component_container_isolated-11] [ERROR] [1718915086.775731595] [coverage_server]: Original error: parameter 'coordinates_in_cartesian_frame' has invalid type: Wrong parameter type, parameter {coordinates_in_cartesian_frame} is of type {bool}, setting it to {string} is not allowed.`

**Comment by SteveMacenski** [comment] 2024-06-20 20:42
`coordinates_in_cartesian_frame` is a bool. I'm saying to fix your `wgs84` to `WGS84`.

**Comment by MarcM0** [comment] 2024-06-20 21:29
I tried that, with coordinates_in_cartesian_frame false and frame_id = "WGS84", it doesnt work. The frame is refered to as 'wgs84' everywhere else in the code so I dont think the capitalized version exists. 
`Invalid GML File or Coordinates: Coordinate system not recognized`

**Comment by SteveMacenski** [comment] 2024-06-20 21:32
I'm looking here: https://github.com/Fields2Cover/Fields2Cover/blob/a068434ba116ee26b0c4405ca177b3a0a4380bf8/src/fields2cover/utils/transformation.cpp#L191 Maybe you need to specify the `datum:` bit? At this point I'm pretty sure this is a ticket for F2C, we're just communicating that information to F2C through this server.

**Comment by MarcM0** [comment] 2024-06-20 22:26
Ok ill ask them, just for notes, ill put some things I tried below
If I set frame to be `frame for f2c message: UTM:10N datum: WGS84`
I get
```
[interactive_waypoint_follower_fields-12] Navigating to with field of size: 5...
[component_container_isolated-11] [INFO] [1718921839.988349952] [bt_navigator]: Begin coverage navigating with outer field of size: 5!
[component_container_isolated-11] ERROR 1: PROJ: proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone
[component_container_isolated-11] ERROR 1: PROJ: proj_create: unrecognized format / unknown name
```
If I set frame = `'EPSG:4326' `
I get 
```
enerating coverage path in EPSG:4326 frame for zone with 5 outer nodes and 0 inner polygons.
[component_container_isolated-11] [INFO] [1718922024.977691647] [controller_server]: Received a goal, begin computing control effort.
[component_container_isolated-11] [WARN] [1718922024.977737502] [controller_server]: No goal checker was specified in parameter 'current_goal_checker'. Server will use only plugin loaded general_goal_checker . This warning will appear once.
[component_container_isolated-11] [WARN] [1718922024.977746566] [controller_server]: No progress checker was specified in parameter 'current_progress_checker'. Server will use only plugin loaded progress_checker . This warning will appear once.
[component_container_isolated-11] [ERROR] [1718922025.038532812] [RPPPathHandler]: Exception in transformPose: "EPSG:4326" passed to lookupTransform argument target_frame does not exist. 
[component_container_isolated-11] [ERROR] [1718922025.038628823] [controller_server]: Unable to transform robot pose into global plan's frame
[component_container_isolated-11] [WARN] [1718922025.038728945] [controller_server]: [follow_path] [ActionServer] Aborting handle.
```

**Comment by MarcM0** [comment] 2024-06-21 13:15
I got it working in the map frame with these points, it seems its really picky about the input points: [[0.05917859077453613, 0.39817535877227783], [29.10934281349182, 52.27346861362457], [69.3645703792572, 50.6134592294693], [60.02701759338379, 4.548198819160461], [0.05917859077453613, 0.39817535877227783]]

**Comment by MarcM0** [comment] 2024-06-21 15:18
Even passing in slightly different points into the opennav demo, [[0.0, 0.0], [0.0, 15.0], [15.0, 15.0], [13.0, 1.0],[0.0, 0.0]], breaks. It seems to be very peculiar about the points it wants

**Comment by SteveMacenski** [comment] 2024-06-21 16:03
Are you properly setting the cartesian param again? The demo starts the robot at a particular location, so obviously if your field doesnt start it in some proximity to that, the controller throws out all the points as out of local costmap bounds. 

I suggest you build up to something like the demo which is a full system integration. Just call the server and get a path visualized in rviz. Then build up to using that path for something useful. 

Closing since WGS84 issue was not caused by this work.

**Closed by SteveMacenski** 2024-06-21 16:03 UTC
